import { StepFunctions } from "aws-sdk";
import { Headers } from "node-fetch";
import { retry } from "./retry";

const domain = process.env.DOMAIN;
const recordExpiryTime = Number(process.env.RECORD_EXPIRY_TIME);

const ALLOWED_ORIGINS = [
  "https://dev.tradetrust.io",
  "https://rinkeby.tradetrust.io",
  "https://www.tradetrust.io",
  "https://tradetrust.io",
];

// reuse the state machine arn and replace stateMachine by execution
// is there a better way ?
const executionArnBasePath = process.env.STATE_MACHINE_ARN?.replace(":stateMachine:", ":execution:");
interface GetNameEvent {
  pathParameters: { executionId: string };
  headers: { [key: string]: any };
}

const stepFunctions = new StepFunctions();

// this function will run through all the events generated by the step machine and will try to find
// - a lambda
// - which provides a name variable as an output.
// From this we will assume that the returned event if any is the expected one
// From the event, we will return
// - the name
// - the expiry time thanks to the execution timestamp and the RECORD_EXPIRY_TIME set
const retrieveExecutionDetailsFromExecutionId = (executionId: string) => async (): Promise<{
  name: string;
  expiryDate: Date;
}> => {
  const data = await stepFunctions
    .getExecutionHistory({
      executionArn: `${executionArnBasePath}:${executionId}`,
    })
    .promise();
  if (data.events) {
    // find the corresponding event
    const event = data.events.find(
      (event: AWS.StepFunctions.Types.HistoryEvent) =>
        event.type === "LambdaFunctionSucceeded" &&
        JSON.parse(event?.lambdaFunctionSucceededEventDetails?.output ?? "")?.name
    );
    // we found an event ? ok let's return the data
    if (event) {
      const date = new Date(event.timestamp);
      date.setSeconds(date.getSeconds() + recordExpiryTime);
      return {
        name: JSON.parse(event?.lambdaFunctionSucceededEventDetails?.output ?? "")?.name,
        expiryDate: date,
      };
    }
  }
  throw new Error("Unable to find the event");
};

export const getExecutionDetails = async (
  event: GetNameEvent
): Promise<{ statusCode: number; headers: { [key: string]: any }; body?: string }> => {
  if (!event.pathParameters.executionId) throw new Error("Please provide an execution ARN");

  console.log("event headers:", event.headers);

  const origin = event.headers.origin || event.headers.Origin;
  const headers = new Headers({
    "Content-Type": "application/json",
  });

  console.log("before allowed origin check headers:", headers);

  if (ALLOWED_ORIGINS.includes(origin)) {
    headers.append("Access-Control-Allow-Origin", origin);
    headers.append("Access-Control-Allow-Credentials", "true");
  } else {
    headers.append("Access-Control-Allow-Credentials", "false");
  }

  console.log("after allowed origin check headers:", headers);

  try {
    // as the execution is asynchronous, we will retry multiple time until we get a result.
    const { name, expiryDate } = await retry(
      retrieveExecutionDetailsFromExecutionId(event.pathParameters.executionId),
      { times: process.env.IS_OFFLINE ? 1 : 10 }
    );
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ name: `${name}.${domain}`, expiryDate }),
    };
  } catch (e) {
    return {
      statusCode: 404,
      headers,
      body: JSON.stringify({}),
    };
  }
};
