import { HistoryEvent, SFN } from "@aws-sdk/client-sfn";
import { retry } from "./retry";

const domain = process.env.DOMAIN;
const recordExpiryTime = Number(process.env.RECORD_EXPIRY_TIME);

const ALLOWED_ORIGINS = [
  "https://dev.tradetrust.io",
  "https://rinkeby.tradetrust.io",
  "https://www.tradetrust.io",
  "https://tradetrust.io",
];

// reuse the state machine arn and replace stateMachine by execution
// is there a better way ?
const executionArnBasePath = process.env.STATE_MACHINE_ARN?.replace(":stateMachine:", ":execution:");
interface GetNameEvent {
  pathParameters: { executionId: string };
  headers: { [key: string]: any };
}

const stepFunctions = new SFN();

// this function will run through all the events generated by the step machine and will try to find
// - a lambda
// - which provides a name variable as an output.
// From this we will assume that the returned event if any is the expected one
// From the event, we will return
// - the name
// - the expiry time thanks to the execution timestamp and the RECORD_EXPIRY_TIME set
const retrieveExecutionDetailsFromExecutionId = (executionId: string) => async (): Promise<{
  name: string;
  expiryDate: Date;
}> => {
  const data = await stepFunctions.getExecutionHistory({
    executionArn: `${executionArnBasePath}:${executionId}`,
  });
  if (data.events) {
    // find the corresponding event
    const event = data.events.find(
      (event: HistoryEvent) =>
        event.type === "LambdaFunctionSucceeded" &&
        JSON.parse(event?.lambdaFunctionSucceededEventDetails?.output ?? "")?.name
    );
    // we found an event ? ok let's return the data
    if (event) {
      const date = new Date(event.timestamp!);
      date.setSeconds(date.getSeconds() + recordExpiryTime);
      return {
        name: JSON.parse(event?.lambdaFunctionSucceededEventDetails?.output ?? "")?.name,
        expiryDate: date,
      };
    }
  }
  throw new Error("Unable to find the event");
};

const getCircularReplacer = () => {
  const ancestors: any[] = [];
  return function (key: string, value: any) {
    if (typeof value !== "object" || value === null) {
      return value;
    }
    // `this` is the object that value is contained in,
    // i.e., its direct parent.
    while (ancestors.length > 0 && ancestors.slice(-1)[0] !== this) {
      ancestors.pop();
    }
    if (ancestors.includes(value)) {
      return "[Circular]";
    }
    ancestors.push(value);
    return value;
  };
};

const stringify = (headers: { [key: string]: any }) => {
  return encodeURI(JSON.stringify(headers, getCircularReplacer()));
};

export const getExecutionDetails = async (
  event: GetNameEvent
): Promise<{ statusCode: number; headers: { [key: string]: any }; body?: string }> => {
  if (!event.pathParameters.executionId) throw new Error("Please provide an execution ARN");

  console.log("event headers:", stringify(event.headers));

  const origin = event.headers.origin || event.headers.Origin;
  let headers;

  if (ALLOWED_ORIGINS.includes(origin)) {
    headers = {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": origin,
      "Access-Control-Allow-Credentials": true,
    };
  } else {
    headers = {
      "Access-Control-Allow-Credentials": false,
    };
  }

  console.log("after allowed origin check headers:", stringify(headers));

  try {
    // as the execution is asynchronous, we will retry multiple time until we get a result.
    const { name, expiryDate } = await retry(
      retrieveExecutionDetailsFromExecutionId(event.pathParameters.executionId),
      { times: process.env.IS_OFFLINE ? 1 : 10 }
    );
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ name: `${name}.${domain}`, expiryDate }),
    };
  } catch (e) {
    return {
      statusCode: 404,
      headers,
      body: JSON.stringify({}),
    };
  }
};
